name:Node.js Cl

no:
 push:
   branches:
     _main

jobs:
 build:

   runs_on ubuntu_latest

strategy:
 matrix:
    node_version: [ 20.x]

steps:
_name: checkout repository
 uses: actions/checkout@v3

_name: Set up Node.js
 uses:action/setup-node@v3
with:
 node-version: $
{{ matrix. node- version}}
   -name: Install dependencies
 run: npm install
   -name: start application 
    rum: npm start
